#!/usr/bin/env bash
#
# create-worktree.sh <n>-<slug>
#
# Create (or reuse) a git worktree for a feature, on branch feature/<n>-<slug>.
# Implements the "shared infra + app port offset" model: the worktree isolates
# code only; the database/Kafka/Redis stack is shared, and the app runs on a
# unique SERVER_PORT so multiple features can run side by side.
#
# Idempotent: re-running for an existing worktree just prints its path/port.
#
# Env:
#   WORKTREE_BASE   base ref to branch from (default: origin/main)
#
# Output (stdout, last two lines, machine-readable):
#   WORKTREE_PATH=<absolute path>
#   SERVER_PORT=<port>
set -euo pipefail

SLUG="${1:-}"
if [ -z "$SLUG" ]; then
  echo "Usage: $0 <n>-<slug>" >&2
  exit 1
fi

ROOT="$(git rev-parse --show-toplevel)"
WT="$ROOT/.worktrees/$SLUG"
BRANCH="feature/$SLUG"
BASE="${WORKTREE_BASE:-origin/main}"

# --- Re-entrant: worktree already exists ---------------------------------
if [ -d "$WT" ]; then
  PORT="$(grep -hs '^SERVER_PORT=' "$WT/.env.worktree" 2>/dev/null | sed 's/SERVER_PORT=//' | head -1 || true)"
  echo "Worktree already exists: $WT (branch $BRANCH, port ${PORT:-unknown})" >&2
  echo "WORKTREE_PATH=$WT"
  echo "SERVER_PORT=${PORT:-8081}"
  exit 0
fi

# --- Create the worktree + branch ----------------------------------------
git -C "$ROOT" fetch --quiet origin 2>/dev/null || true
if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  # Branch already exists locally — attach the worktree to it.
  git -C "$ROOT" worktree add "$WT" "$BRANCH"
else
  git -C "$ROOT" worktree add "$WT" -b "$BRANCH" "$BASE"
fi

# --- Move the staged spec onto the feature branch ------------------------
SPEC_SRC="$ROOT/specs/active/$SLUG"
if [ -d "$SPEC_SRC" ]; then
  mkdir -p "$WT/specs/active"
  mv "$SPEC_SRC" "$WT/specs/active/"
  git -C "$WT" add "specs/active/$SLUG" 2>/dev/null || true
  echo "Moved spec specs/active/$SLUG onto branch $BRANCH" >&2
fi

# --- Copy gitignored files the workflow needs ----------------------------
# A fresh checkout lacks these (they are .gitignore'd), but the skills/scripts
# and local app config depend on them.
mkdir -p "$WT/.claude/config"
for f in \
  ".claude/config/github-project.env" \
  ".claude/settings.local.json" \
  ".env" ".env.local"; do
  if [ -f "$ROOT/$f" ]; then
    mkdir -p "$WT/$(dirname "$f")"
    cp "$ROOT/$f" "$WT/$f"
  fi
done

# --- Assign a free SERVER_PORT (8081..8099; 8080 is reserved for main) ----
USED="$(grep -hs '^SERVER_PORT=' "$ROOT"/.worktrees/*/.env.worktree 2>/dev/null | sed 's/SERVER_PORT=//' || true)"
PORT=""
for p in $(seq 8081 8099); do
  # skip ports already claimed by another worktree
  if printf '%s\n' "$USED" | grep -qx "$p"; then continue; fi
  # skip ports currently listening
  if (exec 3<>"/dev/tcp/127.0.0.1/$p") 2>/dev/null; then exec 3>&- 3<&- 2>/dev/null || true; continue; fi
  PORT="$p"; break
done
if [ -z "$PORT" ]; then
  echo "No free port in 8081-8099; clean up old worktrees and retry." >&2
  exit 1
fi

# --- Per-worktree env + run helper ---------------------------------------
cat > "$WT/.env.worktree" <<EOF
# Generated by create-worktree.sh — per-worktree overrides.
# Shared infra (DB/Kafka/Redis) is reused; only the app port is unique.
SERVER_PORT=$PORT
EOF

cat > "$WT/run-app.sh" <<'EOF'
#!/usr/bin/env bash
# Run this feature's app on its assigned SERVER_PORT against the shared infra
# stack (start that once from the main checkout: `make docker-up`).
# Requires JDK 21 — see CLAUDE.md "Gotchas" for the JAVA_HOME recipe.
set -euo pipefail
cd "$(dirname "$0")"
set -a
[ -f .env ] && . ./.env
[ -f .env.worktree ] && . ./.env.worktree
set +a
echo "Starting app on http://localhost:${SERVER_PORT:-8080} (shared infra)"
exec ./mvnw spring-boot:run
EOF
chmod +x "$WT/run-app.sh"

echo "Created worktree $WT on branch $BRANCH, app port $PORT" >&2
echo "WORKTREE_PATH=$WT"
echo "SERVER_PORT=$PORT"
